### ISSUE TITLE
Inproper Themed Areas

### ISSUE THREAD

**Issue by Strencher** [DevEvil99/Neptune-Discord-Theme#2]
Your theme appears to be incomplete. Many unthemed areas & unreable areas. In general the theme uses very saturated colors, I'd recommend to make them more decent.
# Toasts
![image](https://user-images.githubusercontent.com/46447572/151659319-b6b5a7ad-a640-4b18-bd8e-6ee088667dfa.png)
# Nitro Page in home screen
![image](https://user-images.githubusercontent.com/46447572/151659327-16620905-1799-462a-8b60-50162df7952a.png)
# Authorized Apps Settings
![image](https://user-images.githubusercontent.com/46447572/151659354-0019a544-ee4b-4c9b-a02f-03a892384397.png)
# Connection Settings
![image](https://user-images.githubusercontent.com/46447572/151659364-882fa667-44cd-42c6-b80e-fe1434fa6250.png)
# Discord Intro Settings
![image](https://user-images.githubusercontent.com/46447572/151659377-fd02d599-401a-44e4-b851-55265ec7417c.png)
# Subscription Settings
![image](https://user-images.githubusercontent.com/46447572/151659387-f58e6f42-6d71-4130-882d-3fe480d9e77c.png)
# Appearance Settings
![image](https://user-images.githubusercontent.com/46447572/151659450-77e251b6-2aee-4f53-8bf4-b7fc07fdd348.png)
# Accessibility Settings
![image](https://user-images.githubusercontent.com/46447572/151659470-975e1f15-ba66-4b0d-ae7c-26a7a1c4ca40.png)
# Voice Settings
![image](https://user-images.githubusercontent.com/46447572/151659479-16f6f46c-c446-4a0e-aa81-f68db5f6a31e.png)
# Streamer Mode Settings
![image](https://user-images.githubusercontent.com/46447572/151659485-f2c3065d-c524-4224-8800-9a1a3365ddeb.png)
# Enhanced Settings
![image](https://user-images.githubusercontent.com/46447572/151659495-f0ba0aed-f0bc-4135-8e87-12599f193d77.png)
# Overlay Settings
![image](https://user-images.githubusercontent.com/46447572/151659505-ab77d4c4-096b-46c8-a73c-bdfe088bc2fd.png)
# Date Picker in search
![image](https://user-images.githubusercontent.com/46447572/151659533-4ff5a72d-d60b-432a-83ad-a0403edc7501.png)
# Server Boost settings
![image](https://user-images.githubusercontent.com/46447572/151659546-1c47efd8-cebb-44fb-951c-51c5b45b8d38.png)
# Channel Notices
![image](https://user-images.githubusercontent.com/46447572/151659551-618d7ea7-04b0-4d43-80c9-786289a50672.png)
# Server boosting layer
![image](https://user-images.githubusercontent.com/46447572/151659561-2f8c7750-23ab-4ac6-924b-39d427b17706.png)
# UserPopout footer
![image](https://user-images.githubusercontent.com/46447572/151659575-3e7609d4-6dcc-4ec5-a5ae-2927a84c23ae.png)
# UserPopout Avatar
![image](https://user-images.githubusercontent.com/46447572/151659580-f0d4b76c-cfdf-4c1b-bdc0-b5134971fbf9.png)

**Comment by DevEvil99** [comment]
fixed

**Comment by Strencher** [comment]
The UserPopout isn't fixed yet, the background colors of the footer & avatar still don't match.

**Comment by Strencher** [comment]
The toasts are still broken as well. Here, this snippet helps you to show them, it'll activate the debugger so you can properly theme it.
```js
{
    const Toasts = Object.assign({}, BdApi.findModuleByProps("createToast"), BdApi.findModuleByProps("showToast"));

    Toasts.showToast(
        Toasts.createToast("Some Message", Toasts.ToastType.SUCCESS)
    );
    setTimeout(() => {debugger;}, 1200);
}
```

**Comment by DevEvil99** [comment]
thank you, i fixed them
